-- Verify chain:initial_partition on pg

BEGIN;

SELECT * FROM chain.block_0 WHERE FALSE;
SELECT * FROM chain.block_1m WHERE FALSE;
SELECT * FROM chain.block_2m WHERE FALSE;
SELECT * FROM chain.block_3m WHERE FALSE;
SELECT * FROM chain.block_4m WHERE FALSE;
SELECT * FROM chain.block_5m WHERE FALSE;
SELECT * FROM chain.block_6m WHERE FALSE;
SELECT * FROM chain.block_7m WHERE FALSE;
SELECT * FROM chain.block_8m WHERE FALSE;
SELECT * FROM chain.block_9m WHERE FALSE;
SELECT * FROM chain.block_10m WHERE FALSE;

SELECT * FROM chain.tx_0 WHERE FALSE;
SELECT * FROM chain.tx_1m WHERE FALSE;
SELECT * FROM chain.tx_2m WHERE FALSE;
SELECT * FROM chain.tx_3m WHERE FALSE;
SELECT * FROM chain.tx_4m WHERE FALSE;
SELECT * FROM chain.tx_5m WHERE FALSE;
SELECT * FROM chain.tx_6m WHERE FALSE;
SELECT * FROM chain.tx_7m WHERE FALSE;
SELECT * FROM chain.tx_8m WHERE FALSE;
SELECT * FROM chain.tx_9m WHERE FALSE;
SELECT * FROM chain.tx_10m WHERE FALSE;

SELECT * FROM chain.txOut_0 WHERE FALSE;
SELECT * FROM chain.txOut_1m WHERE FALSE;
SELECT * FROM chain.txOut_2m WHERE FALSE;
SELECT * FROM chain.txOut_3m WHERE FALSE;
SELECT * FROM chain.txOut_4m WHERE FALSE;
SELECT * FROM chain.txOut_5m WHERE FALSE;
SELECT * FROM chain.txOut_6m WHERE FALSE;
SELECT * FROM chain.txOut_7m WHERE FALSE;
SELECT * FROM chain.txOut_8m WHERE FALSE;
SELECT * FROM chain.txOut_9m WHERE FALSE;
SELECT * FROM chain.txOut_10m WHERE FALSE;

SELECT * FROM chain.txIn_0 WHERE FALSE;
SELECT * FROM chain.txIn_1m WHERE FALSE;
SELECT * FROM chain.txIn_2m WHERE FALSE;
SELECT * FROM chain.txIn_3m WHERE FALSE;
SELECT * FROM chain.txIn_4m WHERE FALSE;
SELECT * FROM chain.txIn_5m WHERE FALSE;
SELECT * FROM chain.txIn_6m WHERE FALSE;
SELECT * FROM chain.txIn_7m WHERE FALSE;
SELECT * FROM chain.txIn_8m WHERE FALSE;
SELECT * FROM chain.txIn_9m WHERE FALSE;
SELECT * FROM chain.txIn_10m WHERE FALSE;

ROLLBACK;
