{{- range .Values.networks }}
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: chain-indexer-{{ . }}
  namespace: marlowe-staging
spec:
  components:
  - name: chain-indexer
    type: webservice
    properties:
      cpu: "0.5"
      env:
      - name: NODE_CONFIG
        value: /node/config.json
      - name: DB_NAME
        value: chain-sync-{{ . }}
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            key: username
            name: chain-sync-{{ . }}.marlowe-runtime-database.credentials.postgresql.acid.zalan.do
      - name: DB_PASS
        valueFrom:
          secretKeyRef:
            key: password
            name: chain-sync-{{ . }}.marlowe-runtime-database.credentials.postgresql.acid.zalan.do
      - name: DB_HOST
        value: marlowe-runtime-database.marlowe-staging:5432
      - name: CARDANO_NODE_SOCKET_PATH
        value:
      - name: NODE_CONFIG
        value: http://localhost:8080
      image: ghcr.io/input-output-hk/marlowe-chain-indexer:0.0.2-rc1
      imagePullPolicy: Always
      memory: 1024Mi
  policies:
  - name: local-marlowe-staging
    properties:
      clusters:
      - local
      namespace: marlowe-staging
    type: topology
  workflow:
    mode:
      steps: DAG
    steps:
    - meta:
        alias: Deploy To local-marlowe-staging
      name: local-marlowe-staging
      properties:
        policies:
        - local-marlowe-staging
      type: deploy

{{- end }}
