{{- range $index, $network := .Values.networks }}
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: chain-sync-{{ $network }}
  namespace: marlowe-staging
  annotations:
    app.oam.dev/publishVersion: {{ $.Chart.AppVersion }}
spec:
  components:
  - name: chain-sync-{{ $network }}
    type: webservice
    properties:
      env:
      - name: HOST
        value: 0.0.0.0
      - name: PORT
        value: "3715"
      - name: QUERY_PORT
        value: "3716"
      - name: JOB_PORT
        value: "3720"
      - name: HTTP_PORT
        value: "3782"
      - name: CARDANO_NODE_SOCKET_PATH
        value: /ipc/node.socket
      - name: NODE_CONFIG
        value: /node-config/network/{{ $network }}/cardano-node/config.json
      - name: DB_NAME
        value: chainsync_{{ $network }}
      - name: DB_HOST
        value: marlowe-runtime-database.marlowe-staging:5432
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            key: username
            name: chainsync-{{ $network }}-owner-user.marlowe-runtime-database.credentials.postgresql.acid.zalan.do
            namespace: marlowe-staging
      - name: DB_PASS
        valueFrom:
          secretKeyRef:
            key: password
            name: chainsync-{{ $network }}-owner-user.marlowe-runtime-database.credentials.postgresql.acid.zalan.do
            namespace: marlowe-staging
      cpu: "0.5"
      image: {{ $.Values.images.repo }}/{{ $.Values.images.org }}/marlowe-chain-sync:{{ $.Values.images.tag }}
      imagePullPolicy: Always
      memory: 1024Mi
      ports:
      - expose: true
        port: 3715
        protocol: TCP
      - expose: true
        port: 3716
        protocol: TCP
      - expose: true
        port: 3720
        protocol: TCP
      - expose: true
        port: 3782
        protocol: TCP
      volumeMounts:
        emptyDir:
        - name: ipc
          mountPath: /ipc
        - name: node-config
          mountPath: /node-config
    traits:
    - type: init-container
      properties:
        name: node-config-cloner
        image: alpine/git
        args:
        - clone
        - --single-branch
        - --
        - https://github.com/input-output-hk/cardano-configurations
        - /node-config
        volumes:
        - name: node-config
          path: /node-config

    - type: sidecar
      properties:
        name: socat
        image: alpine/socat
        args:
        - UNIX-LISTEN:/ipc/node.socket,fork
        - TCP-CONNECT:cardano-node-{{ $network }}.vela-system:8090
        volumes:
        - name: ipc
          path: /ipc

  policies:
  - name: local-marlowe-staging
    properties:
      clusters:
      - local
      namespace: marlowe-staging
    type: topology

  workflow:
    mode:
      steps: DAG
    steps:
    - meta:
        alias: Deploy To local-marlowe-staging
      name: local-marlowe-staging
      properties:
        policies:
        - local-marlowe-staging
      type: deploy

{{- end }}
