apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: marlowe-runtime-database
  namespace: marlowe-staging
spec:
  components:
    - type: "postgres-cluster"
      name: marlowe-runtime-database
      properties:
        replicas: 3
        preparedDatabases:
          {{- range $index, $network := .Values.networks }}
          chainsync_{{ $network }}:
            # https://postgres-operator.readthedocs.io/en/latest/user/#default-login-roles
            # chainsync_$network_{owner,writer,reader}_user
            defaultUsers: true

          {{- end }}
