{{- range .Values.networks }}
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: marlowe-sync-{{ . }}
  namespace: marlowe-staging
spec:
  components:
  - name: marlowe-sync
    type: webservice
    properties:
      env:
      - name: HOST
        value: 0.0.0.0
      - name: MARLOWE_SYNC_PORT
        value: "3724"
      - name: MARLOWE_HEADER_SYNC_PORT
        value: "3725"
      - name: MARLOWE_QUERY_PORT
        value: "3726"
      - name: DB_NAME
        value: chainsync_{{ . }}
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            key: username
            name: chainsync-{{ . }}-owner-user.marlowe-runtime-database.credentials.postgresql.acid.zalan.do
            namespace: marlowe-staging
      - name: DB_PASS
        valueFrom:
          secretKeyRef:
            key: password
            name: chainsync_{{ . }}_owner_user.marlowe-runtime-database.credentials.postgresql.acid.zalan.do
            namespace: marlowe-staging
      - name: DB_HOST
        value: marlowe-runtime-database.marlowe-staging:5432
      - name: HTTP_PORT
        value: "3784"
      cpu: "0.5"
      image: {{ $.Values.images.baseUrl }}/marlowe-sync:{{ $.Values.images.tag }}
      imagePullPolicy: Always
      memory: 1024Mi
      ports:
      - expose: true
        port: 3724
        protocol: TCP
      - expose: true
        port: 3725
        protocol: TCP
      - expose: true
        port: 3726
        protocol: TCP
      - expose: true
        port: 3784
        protocol: TCP
  policies:
  - name: local-marlowe-staging
    properties:
      clusters:
      - local
      namespace: marlowe-staging
    type: topology

  workflow:
    mode:
      steps: DAG
    steps:
    - meta:
        alias: Deploy To local-marlowe-staging
      name: local-marlowe-staging
      properties:
        policies:
        - local-marlowe-staging
      type: deploy
{{- end }}
