{{- range $index, $network := .Values.networks }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cardano-network-configs-{{ $network }}
data:
{{- $path := printf "network-configs/%s/*" $network }}
{{ ($.Files.Glob $path).AsConfig | indent 2 }}

{{- end }}
