{ runCommand, generate-run-purescript, generate-playground-purescript, src, diffutils, glibcLocales }:
runCommand "generated-purescript-test"
{
  buildInputs = [ generate-run-purescript generate-playground-purescript diffutils glibcLocales ];
} ''
  set +e
  echo ${toString src}
  cp -a ${src} expected
  cp -a ${src} actual
  chmod -R +w actual
  cd actual/marlowe-dashboard-client
  marlowe-pab-generate-purs
  cd ../marlowe-playground-client
  marlowe-playground-generate-purs
  cd ../..
  diff --brief --recursive expected actual
  EXIT_CODE=$?
  if [[ $EXIT_CODE != 0 ]]
  then
    mkdir -p $out/nix-support
    diff -ur expected actual > $out/actual.diff
    echo "file none $out/actual.diff" > $out/nix-support/hydra-build-products
    echo "*** actual found changes that need addressed first"
    echo "*** Please run \`marlowe-pab-generate-purs\` in"
    echo "*** \`marlowe-dashboard-client\` and \`marlowe-pab-generate-purs\`"
    echo "*** in \`marlowe-playground-client\`and and commit changes."
    
    echo "*** or apply the diff generated by hydra if you don't have nix."
    exit $EXIT_CODE
  else
    echo $EXIT_CODE > $out
  fi
''
