#!/usr/bin/env bash
#
ENVIRONMENT=${ENVIRONMENT:-"preprod"}

eval "$(ssh dev@dapps.aws.iohkdev.io -p 4022 \
  cat /local/network.env \
  | sed -n "/${ENVIRONMENT^^}/s/.*MAIN_//p")"

ssh -N dev@a.dapps.aws.iohkdev.io -p 4022 \
  -L "3700:$PROXY_IP:$PROXY_PORT" \
  -L "3715:$MARLOWE_CHAIN_SYNC_IP:$MARLOWE_CHAIN_SYNC_PORT" \
