{{- range $instanceName, $instance := .Values.instances }}
{{- range $.Values.networks }}
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: marlowe-proxy-{{ . }}-{{ $instanceName }}
  namespace: {{ $.Values.namespace }}
  annotations:
    meta.helm.sh/release-name: {{ $.Values.releaseName }}
    meta.helm.sh/release-namespace: {{ $.Values.namespace }}
spec:
  components:
    - name: marlowe-proxy-{{ . }}-{{ $instanceName }}
      type: webservice
      properties:
        env:
        - name: HOST
          value: 0.0.0.0
        - name: PORT
          value: "3700"
        - name: TRACED_PORT
          value: "3701"
        - name: TRANSFER_PORT
          value: "3729"
        - name: TX_HOST
          value: marlowe-tx-{{ . }}-{{ $instanceName }}.{{ $.Values.namespace }}
        - name: TX_PORT
          value: "3723"
        - name: CONTRACT_HOST
          value: marlowe-contract-{{ . }}-{{ $instanceName }}.{{ $.Values.namespace }}
        - name: LOAD_PORT
          value: "3727"
        - name: CONTRACT_QUERY_PORT
          value: "3728"
        - name: SYNC_HOST
          value: marlowe-sync-{{ . }}-{{ $instanceName }}.{{ $.Values.namespace }}
        - name: MARLOWE_SYNC_PORT
          value: "3724"
        - name: MARLOWE_HEADER_SYNC_PORT
          value: "3725"
        - name: MARLOWE_BULK_SYNC_PORT
          value: "3730"
        - name: MARLOWE_QUERY_PORT
          value: "3726"
        - name: HTTP_PORT
          value: "3786"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ $.Values.otelExporterURL }}:{{ $.Values.otelExporterPort }}
        - name: OTEL_SERVICE_NAME
          value: marlowe-proxy-{{ . }}-{{ $instanceName }}
        cpu: "0.5"
        image: {{ $instance.repo }}/{{ $instance.org }}/marlowe-proxy:{{ $instance.tag }}
        imagePullPolicy: Always
        memory: 1024Mi
      traits:
      - type: expose
        properties:
          annotations:
            "external-dns.alpha.kubernetes.io/hostname": "marlowe-runtime-{{ . }}.{{ $instance.parentDomain }}"
            "service.beta.kubernetes.io/aws-load-balancer-name": "marlowe-runtime-{{ . }}-{{ $instanceName }}"
            "service.beta.kubernetes.io/aws-load-balancer-nlb-target-type": "instance"
            "service.beta.kubernetes.io/aws-load-balancer-scheme": "internet-facing"
            "service.beta.kubernetes.io/aws-load-balancer-type": "external"
          type: LoadBalancer
          ports:
          - port: 3700
          - port: 3701
          - port: 3786


  policies:
  - name: local-{{ $.Values.namespace }}
    properties:
      clusters:
      - local
      namespace: {{ $.Values.namespace }}
    type: topology

  workflow:
    mode:
      steps: DAG
    steps:
    - meta:
        alias: Deploy To local-{{ $.Values.namespace }}
      name: local-{{ $.Values.namespace }}
      properties:
        policies:
        - local-{{ $.Values.namespace }}
      type: deploy
{{- end }}
{{- end }}
