name: "Marlowe-Playground E2E tests"

on:
  schedule:
  - cron: '0 4 * * *'
  push:
    branches: [ SCP-3139/e2e-tests ]
  workflow_dispatch:

jobs:
  plutus-playground-e2e-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Marlowe
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.4'
        cabal-version: '3.2.0.0'

    - name: Setup Nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          substituters        = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Open nix-shell
      working-directory: ./
      run: nix-shell
    - name: Run Marlowe Playground Server
      working-directory: ./
      env:
        GITHUB_CLIENT_ID: 6a3f7261090cca952175
        GITHUB_CLIENT_SECRET: f9c06abeef4031285f152b83e6a307fa46c0be97
        JWT_SIGNATURE: bb0bc0314501f981b0441b90f6771f262afed7743dbb3a8999c7309ebcbb5e867d42ebc0864e325d
        FRONTEND_URL: https://localhost:8009
        GITHUB_CALLBACK_PATH: "/#/gh-oauth-cb"
      run: $(nix-build -A marlowe-playground.server)/bin/marlowe-playground-server webserver &

    - name: Setup NodeJs
      uses: actions/setup-node@v2
      with:
        node-version: '12.16.1'

    - name: Open nix-shell
      working-directory: ./
      run: nix-shell
    - name: Build Marlowe Playground Client
      working-directory: ./marlowe-playground-client
      run: |
        $(nix-build ../default.nix -A marlowe-playground.generate-purescript)/bin/marlowe-playground-generate-purs
        npm install
        npm run build:spago
        npm run build:webpack:dev:vendor
    - name: Run Marlowe Playground Client
      working-directory: ./marlowe-playground-client
      env:
        CLIENT_PORT: 8009
      run: |
        npm run build:webpack:dev &
        while ! echo exit | nc localhost $CLIENT_PORT; do echo "Waiting for playground client on $CLIENT_PORT" && sleep 10; done

    - name: Setup Playwright
      working-directory: ./e2e-tests/
      run: |
        npm install -D @playwright/test
        npx playwright install
  
    - name: Run Tests
      working-directory: ./e2e-tests/
      run: |
        npx playwright test
  
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: html-report
        path: e2e-tests/html-report/index.html
        retention-days: 5